ZipServerBundle\Entity\LogFaixaBairro:
    type: entity
    table: log_faixa_bairro
    indexes:
        log_faixa_bairro_bai_nu_sequencial:
            columns:
                - bai_nu_sequencial
    id:
        fcbNuOrdem:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: fcb_nu_ordem
    fields:
        fcbRadIni:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: fcb_rad_ini
        fcbSufIni:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
            column: fcb_suf_ini
        fcbRadFim:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: fcb_rad_fim
        fcbSufFim:
            type: string
            nullable: false
            length: 3
            options:
                fixed: false
            column: fcb_suf_fim
    oneToOne:
        baiNuSequencial:
            targetEntity: LogBairro
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                bai_nu_sequencial:
                    referencedColumnName: bai_nu_sequencial
            orphanRemoval: false
    lifecycleCallbacks: {  }
