ZipServerBundle\Entity\LogGrandeUsuario:
    type: entity
    table: log_grande_usuario
    indexes:
        log_grande_usuario_cep:
            columns:
                - cep
        log_grande_usuario_ufe_sgloc_nu_sequencialgru_no:
            columns:
                - ufe_sg
                - loc_nu_sequencial
                - gru_no
        log_grande_usuario_bai_nu_sequencial:
            columns:
                - bai_nu_sequencial
        log_grande_usuario_log_nu_sequencial:
            columns:
                - log_nu_sequencial
        log_grande_usuario_loc_nu_sequencial:
            columns:
                - loc_nu_sequencial
        log_grande_usuario_temp:
            columns:
                - temp
    id:
        gruNuSequencial:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            id: true
            column: gru_nu_sequencial
            generator:
                strategy: IDENTITY
    fields:
        ufeSg:
            type: string
            nullable: false
            length: 2
            options:
                fixed: false
            column: ufe_sg
        gruNo:
            type: string
            nullable: false
            length: 96
            options:
                fixed: false
            column: gru_no
        cep:
            type: string
            nullable: false
            length: 16
            options:
                fixed: false
        gruEndereco:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: gru_endereco
        temp:
            type: string
            nullable: true
            length: 8
            options:
                fixed: true
    manyToOne:
        locNuSequencial:
            targetEntity: LogLocalidade
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                loc_nu_sequencial:
                    referencedColumnName: loc_nu_sequencial
            orphanRemoval: false
        logNuSequencial:
            targetEntity: LogLogradouro
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                log_nu_sequencial:
                    referencedColumnName: log_nu_sequencial
            orphanRemoval: false
        baiNuSequencial:
            targetEntity: LogBairro
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                bai_nu_sequencial:
                    referencedColumnName: bai_nu_sequencial
            orphanRemoval: false
    lifecycleCallbacks: {  }
